name: dispatch

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "PR 생성 대상 repository name"
        required: true
        type: choice
        options:
          - all
          - job-web
          - profile-web
          - community-web
          - career-web
          - home-web
          - remember-web

permissions: write-all

jobs:
  create-bump-pr:
    name: Create Bump PR
    runs-on: spot-arm64-small
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_REPO: ${{ inputs.repo }}
    steps:
      # inputs.repo가 all이라면 모든 options에 해당하는 repository에 대해 호출한다
      - name: Set Target Repositories
        run: |
          if [ "$TARGET_REPO" == "all" ]; then
            echo "REPOS=job-web profile-web community-web career-web home-web remember-web" >> $GITHUB_ENV
          else
            echo "REPOS=$TARGET_REPO" >> $GITHUB_ENV
          fi

      - name: Debug selected repos variable
        run: |
          echo "selected repos: $REPOS"

      - name: list
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/dramancompany/repos?type=private

      - name: Trigger rwp-deploy for each repo
        run: |
          for repo in $REPOS; do
            # gh api 명령이 성공한 경우에만 메시지 출력
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/dramancompany/$repo/dispatches \
              -d '{"event_type":"rwp-deploy","client_payload":{"targetPackage":"all"}}' \
              && echo "Successfully triggered 'rwp-deploy' action for $repo" \
              || echo "Failed to trigger 'rwp-deploy' action for $repo" >&2
          done
