name: Linter

on:
  workflow_call:
    inputs:
      nodeVersion:
        description: 'Node.js version'
        type: number
        required: true
      eslintArgs:
        description: 'Additional arguments to pass to the linter'
        type: string
        default: '--max-warnings 0'
      eslintExtensions:
        description: 'File extensions to check with the linter'
        type: string
        default: 'ts,tsx'
      autoFix:
        description: 'Whether the workflow run should try to fix automatically'
        type: boolean
        default: false
      useRememberUI:
        description: '프로젝트 내부에서 github packages remember-ui 사용 여부(토큰 필요)'
        type: boolean
        default: true
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v2

      - name: Node.js ${{ inputs.nodeVersion }} 설정
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: @dramancompany 패키지 사용을 위한 Github 토큰 설정
        if: ${{inputs.useRememberUI}}
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}
          npm config set @dramancompany:registry=https://npm.pkg.github.com/ --location=project

      - name: 의존 모듈 설치
        run: yarn

      - name: 린트 실행
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          prettier: true
          auto_fix: ${{ inputs.autoFix }}
          eslint_args: ${{ inputs.eslintArgs }}
          eslint_extensions: ${{ inputs.eslintExtensions }}

      - name: TSC 실행
        run: npx tsc
