name: Develop 브랜치 최신화 및 Jira 릴리즈

on:
  workflow_call:
    inputs:
      mainBranch:
        description: 'Main branch name'
        type: string
        default: main
      devBranch:
        description: 'Develop branch name'
        type: string
        default: develop
      jiraProjectKey:
        description: 'Jira project key'
        type: string
        required: true
      jiraVersionPrefix:
        description: 'Jira version prefix'
        type: string
        required: true
      jiraIssueDoneStatusName:
        description: 'Jira issue status name that represents `Done` status'
        type: string
        default: 'Done'
      jiraShouldRelease:
        description: 'Whether release jira version'
        type: boolean
        default: true

permissions: write-all

jobs:
  post-release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
      BASE_BRANCH: ${{ inputs.devBranch }}
      MAIN_BRANCH: ${{ inputs.mainBranch }}

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
        with:
          ref: ${{ env.MAIN_BRANCH }}

      - name: Github 토큰 설정
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 브랜치명에서 버전 추출
        run: |
          echo "PACKAGE_VERSION=$(echo ${{ env.HEAD_BRANCH }} | cut -d / -f 2)" >> $GITHUB_ENV

      - name: 버전 태그 지정
        run: |
          git tag -a -m "$PACKAGE_VERSION" $PACKAGE_VERSION $MAIN_BRANCH
          git push origin $PACKAGE_VERSION

      - name: PR 생성 후 머지 (${{ env.HEAD_BRANCH }} -> ${{ env.BASE_BRANCH }})
        env:
          TITLE: Merge '${{ env.PACKAGE_VERSION }}' into ${{ env.BASE_BRANCH }}
          BODY: |
            Merge tag '${{ env.PACKAGE_VERSION }}' into ${{ env.BASE_BRANCH }}.

            > This PR was created automatically for up-to-date develop branch and will merge immediately.
        run: |
          gh pr create --head $MAIN_BRANCH --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
          gh pr merge $MAIN_BRANCH --merge

      - name: 헤드 브랜치 (${{ env.HEAD_BRANCH }}) 삭제
        continue-on-error: true
        run: git push origin --delete $HEAD_BRANCH

      - name: 관련 Jira 이슈 키 추출
        id: extract-issue-keys
        uses: dramancompany/extract-jira-issue-keys@v1.0.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 관련 Jira 이슈 업데이트 및 버전 릴리즈
        uses: dramancompany/jira-release@v1.0.3
        with:
          host: ${{ secrets.JIRA_HOST }}
          email: ${{ secrets.JIRA_EMAIL }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
          issueKeys: ${{ steps.extract-issue-keys.outputs.issueKeys }}
          projectKey: ${{ inputs.jiraProjectKey }}
          versionPrefix: ${{ inputs.jiraVersionPrefix }}
          version: ${{ env.PACKAGE_VERSION }}
          issueDoneStatusName: ${{ inputs.jiraIssueDoneStatusName }}
