name: Create Release PR

on:
  workflow_call:
    inputs:
      usePackageJson:
        description: 'Whether update package.json version'
        type: boolean
        default: true
      packageJsonDirectory:
        description: 'package.json directory to extract current version'
        type: string
        default: './'
      bumpLevel:
        description: 'How to bump package version'
        type: string
      version:
        description: 'Release version'
        type: string
      mainBranch:
        description: 'Main branch name'
        type: string
        default: main
      devBranch:
        description: 'Develop branch name'
        type: string
        default: develop

permissions: write-all

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    if: ${{ inputs.bumpLevel || inputs.version }}

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.devBranch }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Setup Github Token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Current Version
        if: ${{ inputs.usePackageJson }}
        working-directory: ${{ inputs.packageJsonDirectory }}
        run: node -p -e '`CURRENT_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Get New Version
        id: get-new-version
        if: ${{ inputs.usePackageJson }}
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ env.CURRENT_VERSION }}
          level: ${{ inputs.bumpLevel }}

      - name: Create Release Branch
        run: git checkout -b release/${{ inputs.version || steps.get-new-version.outputs.new_version }}

      - name: Bump Version
        if: ${{ inputs.usePackageJson }}
        working-directory: ${{ inputs.packageJsonDirectory }}
        run: npm version ${{ github.event.inputs.bumpLevel }} --no-commit-hooks

      - name: Push Release Branch
        run: git push origin release/${{ inputs.version || steps.get-new-version.outputs.new_version }}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: release/${{ inputs.version || steps.get-new-version.outputs.new_version }}
          BASE_BRANCH: ${{ inputs.mainBranch }}
          TITLE: v${{ inputs.version || steps.get-new-version.outputs.new_version }}
          BODY: |
            v${{ inputs.version || steps.get-new-version.outputs.new_version }}

            > This PR was created by @${{ github.actor }} with manual trigger.
        run: gh pr create --head $HEAD_BRANCH --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
