name: Create Release PR

on:
  workflow_call:
    inputs:
      bumpLevel:
        description: 'How to bump package version'
        type: string
      version:
        description: 'Release version'
        type: string
      mainBranch:
        description: 'Main branch name'
        type: string
        default: main
      devBranch:
        description: 'Develop branch name'
        type: string
        default: develop

permissions: write-all

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    
    if: ${{ inputs.bumpLevel || inputs.version }}

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.devBranch }}
          fetch-depth: 0

      - name: Setup Github Token
        uses: fregante/setup-git-user@v1.1.0
        
      - name: Create New Version
        id: get-new-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.DRAMABOT_TOKEN_FOR_GITHUB_ACTIONS }}
          default_bump: ${{ inputs.bumpLevel }}

      - name: Create Release Branch
        run: git checkout -b release/${{ inputs.version || steps.get-new-version.outputs.new_version }}

      - name: Delete Tag
        run: git push origin --delete ${{ inputs.version || steps.get-new-version.outputs.new_tag }}

      - name: Push Release Branch
        run: git push origin release/${{ inputs.version || steps.get-new-version.outputs.new_version }}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.DRAMABOT_TOKEN_FOR_GITHUB_ACTIONS }}
          HEAD_BRANCH: release/${{ inputs.version || steps.get-new-version.outputs.new_version }}
          BASE_BRANCH: ${{ inputs.mainBranch }}
          TITLE: v${{ inputs.version || steps.get-new-version.outputs.new_version }}
          BODY: |
            v${{ inputs.version || steps.get-new-version.outputs.new_version }}
            > This PR was created by @${{ github.actor }} with manual trigger.
        run: gh pr create --head $HEAD_BRANCH --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
